export const SHIPPING_COMPANIES = [
  { label: 'CJ대한통운', value: 'CJ대한통운' },
  { label: '롯데택배', value: '롯데택배' },
  { label: '한진택배', value: '한진택배' },
  { label: '로젠택배', value: '로젠택배' },
  { label: '우체국택배', value: '우체국택배' },
  { label: 'CU택배', value: 'CU택배' },
  { label: 'GS25택배', value: 'GS25택배' },
  { label: '세븐일레븐택배', value: '세븐일레븐택배' },
  { label: '경동택배', value: '경동택배' },
  { label: '대신택배', value: '대신택배' },
  { label: '일양로지스', value: '일양로지스' },
  { label: '합동택배', value: '합동택배' },
  { label: '천일택배', value: '천일택배' },
  { label: '건영택배', value: '건영택배' },
  { label: '호남택배', value: '호남택배' },
  { label: 'CVSnet', value: 'CVSnet' },
  { label: 'EMS', value: 'EMS' },
  { label: 'DHL', value: 'DHL' },
  { label: 'FedEx', value: 'FedEx' },
  { label: 'UPS', value: 'UPS' },
  { label: '쿠팡로켓배송', value: '쿠팡로켓배송' },
  { label: '마켓컬리', value: '마켓컬리' },
  { label: 'SSG닷컴', value: 'SSG닷컴' },
  { label: '굿스플로', value: '굿스플로' },
  { label: '드림택배', value: '드림택배' },
  { label: '농협택배', value: '농협택배' },
  { label: '성원글로벌카고', value: '성원글로벌카고' },
  { label: '슈퍼박스', value: '슈퍼박스' },
  { label: '부릉', value: '부릉' },
  { label: '바로고', value: '바로고' },
  { label: '메쉬코리아(부탁해)', value: '메쉬코리아(부탁해)' },
  { label: '직방택배', value: '직방택배' },
  { label: '기타', value: '기타' },
] as const;

export type ShippingCompanyValue =
  (typeof SHIPPING_COMPANIES)[number]['value'];
