import type { Metadata } from 'next';
import './globals.css';
import styles from './layout.module.css';
import Sidebar from '../components/sidebar';
import ReactQueryProvider from './ReactQueryProvider';
import { menus } from '@/constants/menus';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.rootLayoutContainer}>
        <ReactQueryProvider>
          <Sidebar>
            <Sidebar.MenusConatiner>
              {menus.map((menu) => (
                <Sidebar.Menus
                  key={menu.href}
                  href={menu.href}
                  text={menu.text}
                />
              ))}
            </Sidebar.MenusConatiner>
            <Sidebar.MenusConatiner>
              <Sidebar.Menus href="/" text="로그아웃" />
            </Sidebar.MenusConatiner>
          </Sidebar>
          <div className={styles.contentContainer}>{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
